database:
  host: localhost
  port: 5432
  name: account-db
  username: user-test
  password: password

spring:
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual_immediate
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-serializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    consumer:
      group-id: account-service-group
      key-deserializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArraySerializer
      enable-auto-commit: false
      auto-offset-reset: earliest